<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>559d9d87-4adf-47a8-8f48-d6782b88070d</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.14"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.18">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AsistOff.MES.Configuration.Api\AsistOff.MES.Configuration.Api.csproj" />
      <ProjectReference Include="..\AsistOff.MES.Multitenancy\AsistOff.MES.Multitenancy.csproj" />
      <ProjectReference Include="..\AsistOff.MES.Shared.Infrastructure\AsistOff.MES.Shared.Infrastructure.csproj" />
      <ProjectReference Include="..\AsistOff.MES.Users.Api\AsistOff.MES.Users.Api.csproj" />
    </ItemGroup>

</Project>
