<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AsistOff.MES.Configuration.Infrastructure\AsistOff.MES.Configuration.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Contracts\Warehouses\" />
    </ItemGroup>

</Project>
