<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.7" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AsistOff.MES.Shared.Abstractions\AsistOff.MES.Shared.Abstractions.csproj" />
    <ProjectReference Include="..\..\AsistOff.MES.Multitenancy\AsistOff.MES.Multitenancy.csproj" />
    <ProjectReference Include="..\..\AsistOff.MES.Multitenancy.Contracts\AsistOff.MES.Multitenancy.Contracts.csproj" />
    <ProjectReference Include="..\..\AsistOff.MES.Configuration.Application\AsistOff.MES.Configuration.Application.csproj" />
    <ProjectReference Include="..\..\AsistOff.MES.Configuration.Core\AsistOff.MES.Configuration.Core.csproj" />
    <ProjectReference Include="..\..\AsistOff.MES.Production.Application\AsistOff.MES.Production.Application.csproj" />
    <ProjectReference Include="..\..\AsistOff.MES.Production.Core\AsistOff.MES.Production.Core.csproj" />
    <ProjectReference Include="..\..\AsistOff.MES.Users.Application\AsistOff.MES.Users.Application.csproj" />
    <ProjectReference Include="..\..\AsistOff.MES.Users.Core\AsistOff.MES.Users.Core.csproj" />
  </ItemGroup>

</Project>
