// <auto-generated />
using System;
using AsistOff.MES.Shared.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AsistOff.MES.Shared.Infrastructure.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20250827202107_products")]
    partial class products
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Code" }, "IX_Departments_Code");

                    b.HasIndex(new[] { "TenantId" }, "IX_Departments_TenantId");

                    b.HasIndex(new[] { "TenantId", "Code" }, "IX_Departments_TenantId_Code")
                        .IsUnique();

                    b.ToTable("Departments", "config");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.MeasureUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaseUnitId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ConversionFactor")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SyncId")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Type");

                    b.HasIndex("TenantId", "Symbol", "Type")
                        .IsUnique();

                    b.ToTable("MeasureUnits", "config");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("RatePerHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,5)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_Employees_DepartmentId");

                    b.HasIndex(new[] { "Identifier" }, "IX_Employees_Identifier");

                    b.HasIndex(new[] { "TenantId" }, "IX_Employees_TenantId");

                    b.HasIndex(new[] { "TenantId", "Identifier" }, "IX_Employees_TenantId_Identifier")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_Employees_UserId");

                    b.ToTable("Operators", "config");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Ean")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ProductGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScanBy")
                        .HasColumnType("integer");

                    b.Property<string>("SyncId")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("Ean");

                    b.HasIndex("ProductGroupId");

                    b.HasIndex("ScanBy");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Products", "config");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.ProductGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("SyncId")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("ProductGroups", "config");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.ProductMeasureUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConversionFactor")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasDefaultValue(1m);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MeasureUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SyncId")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.HasIndex("MeasureUnitId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ProductId", "MeasureUnitId")
                        .IsUnique();

                    b.ToTable("ProductMeasureUnits", "config");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.ProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("PLN");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MeasureUnitId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MinQuantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SyncId")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MeasureUnitId");

                    b.HasIndex("PriceType");

                    b.HasIndex("ProductId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ValidFrom");

                    b.HasIndex("ValidTo");

                    b.HasIndex("ProductId", "PriceType", "ValidFrom", "ValidTo");

                    b.ToTable("ProductPrices", "config");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyncId")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_Warehouses_Name");

                    b.HasIndex(new[] { "TenantId" }, "IX_Warehouses_TenantId");

                    b.ToTable("Warehouses", "config");
                });

            modelBuilder.Entity("AsistOff.MES.Users.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsTenantAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.MeasureUnit", b =>
                {
                    b.HasOne("AsistOff.MES.Configuration.Domain.Entities.MeasureUnit", "BaseUnit")
                        .WithMany("DerivedUnits")
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.Operator", b =>
                {
                    b.HasOne("AsistOff.MES.Configuration.Domain.Entities.Department", "Department")
                        .WithMany("Operators")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.Product", b =>
                {
                    b.HasOne("AsistOff.MES.Configuration.Domain.Entities.ProductGroup", "ProductGroup")
                        .WithMany("Products")
                        .HasForeignKey("ProductGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProductGroup");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.ProductGroup", b =>
                {
                    b.HasOne("AsistOff.MES.Configuration.Domain.Entities.ProductGroup", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.ProductMeasureUnit", b =>
                {
                    b.HasOne("AsistOff.MES.Configuration.Domain.Entities.MeasureUnit", "MeasureUnit")
                        .WithMany("ProductMeasureUnits")
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AsistOff.MES.Configuration.Domain.Entities.Product", "Product")
                        .WithMany("ProductMeasureUnits")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasureUnit");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.ProductPrice", b =>
                {
                    b.HasOne("AsistOff.MES.Configuration.Domain.Entities.MeasureUnit", "MeasureUnit")
                        .WithMany()
                        .HasForeignKey("MeasureUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AsistOff.MES.Configuration.Domain.Entities.Product", "Product")
                        .WithMany("ProductPrices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasureUnit");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.Department", b =>
                {
                    b.Navigation("Operators");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.MeasureUnit", b =>
                {
                    b.Navigation("DerivedUnits");

                    b.Navigation("ProductMeasureUnits");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductMeasureUnits");

                    b.Navigation("ProductPrices");
                });

            modelBuilder.Entity("AsistOff.MES.Configuration.Domain.Entities.ProductGroup", b =>
                {
                    b.Navigation("ChildGroups");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
